---
# defaults file for k3s-server

# temporary directory (marked for removal)
tmp_dir: /tmp/k3s-server
  
# K3s variables
k3s:
  version: v1.28.12+k3s1
  path:
    bin: /usr/local/bin/k3s
    install: "{{ tmp_dir }}/k3s_install.sh"
    node_token: /var/lib/rancher/k3s/server/node-token
#  node_token: lookup('file', '/var/lib/rancher/k3s/server/node-token')
