servers:
  hosts:
    k3s-master-01: # tainted master
      ansible_host: 10.0.0.11
    k3s-master-02: # decicated control plane
      ansible_host: 10.0.0.12
agents:
  hosts:
    k3s-worker-01:
      ansible_host: 10.0.0.21
    k3s-worker-02:
      ansible_host: 10.0.0.22
